import { expect, test } from '@playwright/test';

const accounts = [
    ['brgyrosario@gmail.com', 'Barangay Rosario', 390],
    ['brgymaybunga@gmail.com', 'Barangay Maybunga', 768],
    ['brgystothomas@gmail.com', 'Barangay Sto. Thomas', 1440],
];
for (const [email, name, width] of accounts) {
    test(`seller ${name} at ${width}px`, async ({ page }, testInfo) => {
        await page.setViewportSize({ width, height: 1000 });
        await page.addInitScript(() => { if (!localStorage.getItem('agrifarm-theme')) localStorage.setItem('agrifarm-theme', 'light'); });
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.goto('/login');
        await page.getByLabel('Email address').fill(email);
        await page.getByLabel('Password', { exact: true }).fill('AgriFarm123!');
        await page.getByRole('button', { name: 'Login', exact: true }).click();
        await expect(page).toHaveURL(/\/seller\/dashboard$/);
        await expect(page.getByRole('heading', { name: 'Sales overview' })).toBeVisible();
        await expect(page.getByRole('button', { name: 'Add product' })).toHaveCount(0);
        await expect(page.getByText('Seller Dashboard', { exact: true })).toHaveCount(0);
        await expect(page.getByText(/Good morning/)).toHaveCount(0);
        await page.getByLabel('Sales period').selectOption('This month');
        await expect(page.getByText('No sales this month')).toBeVisible();
        await page.getByLabel('Sales period').selectOption('This week');
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
        await page.screenshot({ path: testInfo.outputPath(`seller-${width}.png`), fullPage: true });
        await page.getByRole('button', { name: 'Manage products' }).click();
        await expect(page.getByRole('heading', { name: 'Products', exact: true })).toBeVisible();
        await page.getByRole('button', { name: 'Add product', exact: true }).click();
        const productModal = page.getByRole('dialog', { name: 'Add product' });
        await expect(productModal).toBeVisible();
        await page.keyboard.press('Escape');
        await expect(productModal).not.toBeVisible();
        await page.getByRole('button', { name: 'Add product', exact: true }).click();
        await productModal.getByRole('button', { name: 'Add product', exact: true }).click();
        await expect(page.getByLabel('Product name', { exact: true })).toHaveAttribute('aria-invalid', 'true');
        await page.getByLabel('Product name', { exact: true }).fill('Fresh Pechay');
        await page.getByLabel('Category', { exact: true }).selectOption('Vegetables');
        await page.getByLabel('Description', { exact: false }).fill('Freshly harvested from our barangay garden.');
        await page.getByLabel('Price (PHP)', { exact: true }).fill('35');
        await page.getByLabel('Selling unit', { exact: true }).selectOption('bunch');
        await page.getByLabel('Available stock', { exact: true }).fill('3');
        await page.locator('#product-photo').setInputFiles({ name: 'pechay.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII=', 'base64') });
        await productModal.getByRole('button', { name: 'Add product', exact: true }).click();
        await expect(productModal).not.toBeVisible();
        await expect(page.getByRole('status')).toHaveText('Product added successfully.');
        await expect(page.locator('.seller-product-item')).toHaveCount(1);
        await page.reload();
        await expect(page.locator('.seller-product-item h2')).toHaveText('Fresh Pechay');
        await expect(page.locator('.seller-product-item')).toContainText('35.00');
        await expect(page.locator('.seller-product-item')).toContainText('3 bunch available');
        await expect.poll(() => page.locator('.seller-product-item img').evaluate(img => img.complete && img.naturalWidth > 0)).toBeTruthy();
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
        await page.screenshot({ path: testInfo.outputPath(`saved-products-${width}.png`), fullPage: true });
        for (const section of ['Orders', 'Forecasting', 'Analytics', 'Store Profile', 'Dashboard']) {
            if (width <= 800) await page.getByRole('button', { name: 'Toggle seller navigation' }).click();
            await page.getByRole('navigation', { name: 'Seller navigation' }).getByRole('button', { name: section, exact: true }).click();
            if (section === 'Store Profile') await expect(page.getByLabel('Email address', { exact: true })).toHaveValue(email);
            else if (section !== 'Dashboard') await expect(page.getByRole('heading', { name: section, exact: true })).toBeVisible();
            expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
        }
        await page.locator('.seller-account').click();
        await expect(page.getByText('SELLER CENTER', { exact: true })).toHaveCount(0);
        await page.getByRole('button', { name: 'Notifications', exact: true }).click();
        await expect(page.getByText('No notifications yet')).toBeVisible();
        await page.keyboard.press('Escape');
        await expect(page.getByText('No notifications yet')).toHaveCount(0);
        await page.getByLabel('Choose profile photo').setInputFiles({ name: 'profile.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII=', 'base64') });
        await page.getByRole('button', { name: 'Save photo', exact: true }).click();
        await expect(page.getByRole('status')).toContainText('Profile photo updated successfully.');
        await page.reload();
        await expect(page.locator('.seller-account img')).toBeVisible();
        expect(await page.locator('.seller-account img').evaluate(img => img.complete && img.naturalWidth > 0)).toBeTruthy();
        if (await page.getByRole('dialog').isVisible()) await page.getByRole('button', { name: 'Close add product' }).click();
        await page.getByRole('button', { name: 'Switch to dark mode' }).click();
        await expect(page.locator('html')).toHaveClass(/dark/);
        await page.reload();
        await expect(page.locator('html')).toHaveClass(/dark/);
        await page.getByRole('button', { name: 'Notifications', exact: true }).click();
        await expect(page.getByText('No notifications yet')).toBeVisible();
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
        await page.screenshot({ path: testInfo.outputPath(`profile-dark-${width}.png`), fullPage: true });
        await page.getByRole('button', { name: 'Close notifications' }).click();
        if (width <= 800) await page.getByRole('button', { name: 'Toggle seller navigation' }).click();
        await page.getByRole('navigation', { name: 'Seller navigation' }).getByRole('button', { name: 'Dashboard', exact: true }).click();
        await expect(page.getByRole('heading', { name: 'Sales overview' })).toBeVisible();
        await expect(page.locator('.seller-account > span').filter({ hasText: name })).toBeVisible();
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
        await page.screenshot({ path: testInfo.outputPath(`dashboard-dark-${width}.png`), fullPage: true });
        await page.locator('.seller-account').click();
        if (await page.getByRole('dialog').isVisible()) await page.getByRole('button', { name: 'Close add product' }).click();
        await page.getByRole('button', { name: 'Switch to light mode' }).click();
        await expect(page.locator('html')).not.toHaveClass(/dark/);
        await page.getByRole('button', { name: 'Remove photo' }).click();
        await expect(page.getByRole('status')).toContainText('Profile photo removed.');
        await expect(page.locator('.seller-account img')).toHaveCount(0);
        await page.getByLabel('Barangay / store name').fill(`${name} Urban Farm`);
        await page.getByRole('button', { name: 'Save profile', exact: true }).click();
        await expect(page.getByRole('status')).toContainText('Profile updated successfully.');
        await page.reload();
        await expect(page.getByLabel('Barangay / store name')).toHaveValue(`${name} Urban Farm`);
        await page.getByLabel('Current password', { exact: true }).fill('incorrect');
        await page.getByLabel('New password', { exact: true }).fill('UpdatedSeller123!');
        await page.getByLabel('Confirm new password', { exact: true }).fill('UpdatedSeller123!');
        await page.getByRole('button', { name: 'Update password', exact: true }).click();
        await expect(page.getByLabel('Current password', { exact: true })).toHaveAttribute('aria-invalid', 'true');
        await page.getByLabel('Current password', { exact: true }).fill('AgriFarm123!');
        await page.getByRole('button', { name: 'Show new password', exact: true }).click();
        await expect(page.getByLabel('New password', { exact: true })).toHaveAttribute('type', 'text');
        await page.getByRole('button', { name: 'Update password', exact: true }).click();
        await expect(page.getByRole('status')).toContainText('Password updated successfully.');
        await expect(page.getByLabel('New password', { exact: true })).toHaveValue('');
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
        await page.screenshot({ path: testInfo.outputPath(`profile-${width}.png`), fullPage: true });
        await expect(page.getByLabel('Email address', { exact: true })).toHaveValue(email);
        if (width <= 800) await page.getByRole('button', { name: 'Toggle seller navigation' }).click();
        await page.getByRole('button', { name: 'Sign out' }).click();
        await expect(page).toHaveURL(/\/login$/);
        await page.getByLabel('Email address').fill(email);
        await page.getByLabel('Password', { exact: true }).fill('UpdatedSeller123!');
        await page.getByRole('button', { name: 'Login', exact: true }).click();
        await expect(page).toHaveURL(/\/seller\/dashboard$/);
        expect(errors).toEqual([]);
    });
}
