<?php

return [
    'preview_product_keys' => [
        'pechay', 'tomatoes', 'eggplant', 'cucumber', 'carrots', 'lettuce',
        'kangkong', 'okra', 'beans', 'basil', 'calamansi', 'squash',
    ],
    'barangay_seller_names' => [
        'Bagong Ilog' => ['Barangay Bagong Ilog'],
        'Bagong Katipunan' => ['Barangay Bagong Katipunan'],
        'Bambang' => ['Barangay Bambang'],
        'Buting' => ['Barangay Buting'],
        'Caniogan' => ['Barangay Caniogan'],
        'Dela Paz' => ['Barangay Dela Paz'],
        'Kalawaan' => ['Barangay Kalawaan'],
        'Kapasigan' => ['Barangay Kapasigan'],
        'Kapitolyo' => ['Barangay Kapitolyo'],
        'Malinao' => ['Barangay Malinao'],
        'Manggahan' => ['Barangay Manggahan'],
        'Maybunga' => ['Barangay Maybunga'],
        'Oranbo' => ['Barangay Oranbo'],
        'Palatiw' => ['Barangay Palatiw'],
        'Pinagbuhatan' => ['Barangay Pinagbuhatan'],
        'Pineda' => ['Barangay Pineda'],
        'Rosario' => ['Barangay Rosario'],
        'Sagad' => ['Barangay Sagad'],
        'San Antonio' => ['Barangay San Antonio'],
        'San Joaquin' => ['Barangay San Joaquin'],
        'San Jose' => ['Barangay San Jose'],
        'San Miguel' => ['Barangay San Miguel'],
        'San Nicolas' => ['Barangay San Nicolas'],
        'Santolan' => ['Barangay Santolan'],
        'Sta. Cruz' => ['Barangay Sta. Cruz'],
        'Sta. Lucia' => ['Barangay Sta. Lucia'],
        'Sta. Rosa' => ['Barangay Sta. Rosa'],
        'Sto. Tomas' => ['Barangay Sto. Tomas', 'Barangay Sto. Thomas'],
        'Sumilang' => ['Barangay Sumilang'],
        'Ugong' => ['Barangay Ugong'],
    ],
    'barangay_seller_emails' => [
        'Bagong Ilog' => ['brgybagongilog@gmail.com'],
        'Bagong Katipunan' => ['brgybagongkatipunan@gmail.com'],
        'Bambang' => ['brgybambang@gmail.com'],
        'Buting' => ['brgybuting@gmail.com'],
        'Caniogan' => ['brgycaniogan@gmail.com'],
        'Dela Paz' => ['brgydelapaz@gmail.com'],
        'Kalawaan' => ['brgykalawaan@gmail.com'],
        'Kapasigan' => ['brgykapasigan@gmail.com'],
        'Kapitolyo' => ['brgykapitolyo@gmail.com'],
        'Malinao' => ['brgymalinao@gmail.com'],
        'Manggahan' => ['brgymanggahan@gmail.com'],
        'Maybunga' => ['brgymaybunga@gmail.com'],
        'Oranbo' => ['brgyoranbo@gmail.com'],
        'Palatiw' => ['brgypalatiw@gmail.com'],
        'Pinagbuhatan' => ['brgypinagbuhatan@gmail.com'],
        'Pineda' => ['brgypineda@gmail.com'],
        'Rosario' => ['brgyrosario@gmail.com'],
        'Sagad' => ['brgysagad@gmail.com'],
        'San Antonio' => ['brgysanantonio@gmail.com'],
        'San Joaquin' => ['brgysanjoaquin@gmail.com'],
        'San Jose' => ['brgysanjose@gmail.com'],
        'San Miguel' => ['brgysanmiguel@gmail.com'],
        'San Nicolas' => ['brgysannicolas@gmail.com'],
        'Santolan' => ['brgysantolan@gmail.com'],
        'Sta. Cruz' => ['brgystacruz@gmail.com'],
        'Sta. Lucia' => ['brgystalucia@gmail.com'],
        'Sta. Rosa' => ['brgystarosa@gmail.com'],
        'Sto. Tomas' => ['brgystotomas@gmail.com'],
        'Sumilang' => ['brgysumilang@gmail.com'],
        'Ugong' => ['brgyugong@gmail.com'],
    ],
];
